---
- name: Include dynamic variables

- hosts: all
  import_playbook: ../dynamic-assignments/env-vars.yml

- name: include env files
  import_playbook: ../static-assignments/common.yml
  tags:
    - always

- hosts: uat-webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/uat-webservers.yml

- hosts: db
- name: Installing db
  import_playbook: ../static-assignments/db.yml
  
 - hosts: lb
- name: import Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required
