---
- hosts: all
- name: Include dynamic variables
  import_playbook: ../dynamic-assignments/env-vars.yml

- name: include env files
  import_playbook: ../static-assignments/common.yml
  tags:
    - always

- hosts: uat-webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/uat-webservers.yml

- hosts: db
- name: Installing db
  import_playbook: ../static-assignments/db.yml
